/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LeftSideBar: typeof import('./src/components/LeftSideBar.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    RightSideBar: typeof import('./src/components/RightSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeLine: typeof import('./src/components/TimeLine.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
