/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/common/AppBar.vue')['default']
    CanvasRuler: typeof import('./src/components/editor/canvas/CanvasRuler.vue')['default']
    CanvasSettings: typeof import('./src/components/editor/rightsidebar/CanvasSettings.vue')['default']
    ColorPicker: typeof import('./src/components/controls/ColorPicker.vue')['default']
    DashboardContent: typeof import('./src/components/dashboard/DashboardContent.vue')['default']
    DashboardSideBar: typeof import('./src/components/dashboard/DashboardSideBar.vue')['default']
    DialogList: typeof import('./src/components/editor/dialogs/DialogList.vue')['default']
    DrawingCanvas: typeof import('./src/components/editor/canvas/DrawingCanvas.vue')['default']
    ExportDialog: typeof import('./src/components/editor/dialogs/ExportDialog.vue')['default']
    FileUploader: typeof import('./src/components/editor/leftsidebar/FileUploader.vue')['default']
    FitZoom: typeof import('./src/components/editor/rightsidebar/FitZoom.vue')['default']
    FormContainer: typeof import('./src/components/common/FormContainer.vue')['default']
    ImageLibrary: typeof import('./src/components/editor/leftsidebar/ImageLibrary.vue')['default']
    Input: typeof import('./src/components/controls/Input.vue')['default']
    InputGroup: typeof import('./src/components/controls/InputGroup.vue')['default']
    KeyFrame: typeof import('./src/components/editor/timeline/KeyFrame.vue')['default']
    KeyFramesTrack: typeof import('./src/components/editor/timeline/KeyFramesTrack.vue')['default']
    LayerList: typeof import('./src/components/editor/leftsidebar/LayerList.vue')['default']
    LeftSideBar: typeof import('./src/components/editor/LeftSideBar.vue')['default']
    MainContent: typeof import('./src/components/editor/MainContent.vue')['default']
    PlaybackButtons: typeof import('./src/components/editor/timeline/PlaybackButtons.vue')['default']
    ProjectFilter: typeof import('./src/components/dashboard/ProjectFilter.vue')['default']
    ProjectPaginator: typeof import('./src/components/dashboard/ProjectPaginator.vue')['default']
    ProjectSettings: typeof import('./src/components/editor/leftsidebar/ProjectSettings.vue')['default']
    ProjectsGrid: typeof import('./src/components/dashboard/ProjectsGrid.vue')['default']
    PropertySettings: typeof import('./src/components/editor/rightsidebar/PropertySettings.vue')['default']
    RightSideBar: typeof import('./src/components/editor/RightSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsAppearance: typeof import('./src/components/editor/rightsidebar/SettingsAppearance.vue')['default']
    SettingsShape: typeof import('./src/components/editor/rightsidebar/SettingsShape.vue')['default']
    SettingsTransforms: typeof import('./src/components/editor/rightsidebar/SettingsTransforms.vue')['default']
    ShapeLibrary: typeof import('./src/components/editor/leftsidebar/ShapeLibrary.vue')['default']
    Slider: typeof import('./src/components/controls/Slider.vue')['default']
    TextCreator: typeof import('./src/components/editor/leftsidebar/TextCreator.vue')['default']
    TimeLine: typeof import('./src/components/editor/TimeLine.vue')['default']
    TimelineContent: typeof import('./src/components/editor/timeline/TimelineContent.vue')['default']
    TimelineFooter: typeof import('./src/components/editor/timeline/TimelineFooter.vue')['default']
    TimelineHeader: typeof import('./src/components/editor/timeline/TimelineHeader.vue')['default']
    TimeTrack: typeof import('./src/components/editor/timeline/TimeTrack.vue')['default']
    ToolBar: typeof import('./src/components/editor/ToolBar.vue')['default']
    TopBar: typeof import('./src/components/editor/TopBar.vue')['default']
    UserMenu: typeof import('./src/components/common/UserMenu.vue')['default']
  }
}
