/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/common/AppBar.vue')['default']
    CanvasRuler: typeof import('./src/components/editor/canvas/CanvasRuler.vue')['default']
    DrawingCanvas: typeof import('./src/components/editor/canvas/DrawingCanvas.vue')['default']
    FormContainer: typeof import('./src/components/common/FormContainer.vue')['default']
    LeftSideBar: typeof import('./src/components/editor/LeftSideBar.vue')['default']
    MainContent: typeof import('./src/components/editor/MainContent.vue')['default']
    OptionsMenu: typeof import('./src/components/editor/OptionsMenu.vue')['default']
    PlaybackButtons: typeof import('./src/components/editor/timeline/PlaybackButtons.vue')['default']
    RightSideBar: typeof import('./src/components/editor/RightSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeLine: typeof import('./src/components/editor/TimeLine.vue')['default']
    TimelineContent: typeof import('./src/components/editor/timeline/TimelineContent.vue')['default']
    TimelineFooter: typeof import('./src/components/editor/timeline/TimelineFooter.vue')['default']
    TimelineHeader: typeof import('./src/components/editor/timeline/TimelineHeader.vue')['default']
    TimeTrack: typeof import('./src/components/editor/timeline/TimeTrack.vue')['default']
    ToolBar: typeof import('./src/components/editor/ToolBar.vue')['default']
    TopBar: typeof import('./src/components/editor/TopBar.vue')['default']
    UserMenu: typeof import('./src/components/common/UserMenu.vue')['default']
  }
}
